# Build the materials and bush to build branch
name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: git-checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          make                                    # Build the exercises and challenges
          mkdir build                             # Collect the build
          cp -r challenges_assignment build/.
          cp -r exercises_assignment build/.
          cp requirements.txt build/.
          cp README.md build/.
    
      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build
          FOLDER: build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build: ({sha}) {msg}"
